import type { Metadata } from "next"
import { Montserrat, Inter } from "next/font/google"
import "./globals.css"
import Header from "@/components/sections/Header"
import Footer from "@/components/sections/Footer"
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const montserrat = Montserrat({
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-BR" className={cn("h-full", montserrat.className, "font-sans", inter.variable)}>
			<body className="min-h-full container px-3 mx-auto flex flex-col antialiased">
				<Header />
				{children}
        <Footer />
			</body>
		</html>
	)
}
