import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"
import Header from "@/components/sections/Header"
import Footer from "@/components/sections/Footer"

const montserrat = Montserrat({
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-BR" className={`${montserrat.className} h-full`}>
			<body className="min-h-full container px-3 mx-auto flex flex-col antialiased">
				<Header />
				{children}
        <Footer />
			</body>
		</html>
	)
}
